import React from 'react'
import ReactDOM from 'react-dom'
// import App from './Hook'
// import App from './跨组件的通信/01_跨组件的通信_context.js'
// import '../src/组件通信的案例/style.css'
// import App from './跨组件的通信/全局事件传递'
// import App from './受控与非受控组件/01_ref的使用'
// import App from './受控与非受控组件/02_受控组件的基本使用'
// import App from './受控与非受控组件/03_受控组件_selsct'
// import App from './受控与非受控组件/04_受控组件_多个输入'
// import App from './demo/Game'
import App from './router/'
import { BrowserRouter } from "react-router-dom"
import App from './Theme'
// import '../src/react实现slot/style.css'
import './demo/style.css'
// import './index.css'
ReactDOM.render(<App />, document.getElementById('root'))